package Main;

import Resources.Circuit.Circuit;
import Resources.Components.Component;
import Resources.Components.Gates.*;
import Resources.Components.*;
import Resources.Components.Variable;
import Resources.Components.Wire;
import Resources.Enums.MouseType;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class Main extends javax.swing.JFrame {
    Circuit circuit = new Circuit();
    MouseType type;
    Graphics gp;
    
    public Main() {
        initComponents();
        type = MouseType.None;
        gp = DrawingPanel.getGraphics();
        DrawingPanel.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                if(SwingUtilities.isLeftMouseButton(e)){
                    Point org = e.getPoint();
                    circuit.switchVariable(e);
                    repaint();
                    switch(type){
                        case MouseType.And -> {
                            circuit.addComponent(org, new And(org));
                            circuit.getComponentList().getLast().setDrawValue(true);
                            repaint();
                        }
                        case MouseType.NAnd -> {
                            circuit.addComponent(org, new NAnd(org));
                            circuit.getComponentList().getLast().setDrawValue(true);
                            repaint();
                        }
                        case MouseType.Or -> {
                            circuit.addComponent(org, new Or(org));
                            circuit.getComponentList().getLast().setDrawValue(true);
                            repaint();
                        }
                        case MouseType.NOr -> {
                            circuit.addComponent(org, new NOr(org));
                            circuit.getComponentList().getLast().setDrawValue(true);
                            repaint();
                        }
                        case MouseType.XOr -> {
                            circuit.addComponent(org, new XOr(org));
                            circuit.getComponentList().getLast().setDrawValue(true);
                            repaint();
                        }
                        case MouseType.XNOr -> {
                            circuit.addComponent(org, new XNOr(org));
                            circuit.getComponentList().getLast().setDrawValue(true);
                            repaint();
                        }
                        case MouseType.Not -> {
                            circuit.addComponent(org, new Not(org));
                            circuit.getComponentList().getLast().setDrawValue(true);
                            repaint();
                        }///
                        case MouseType.Variable -> {
                            circuit.addComponent(org, new Variable(org));
                            circuit.getComponentList().getLast().setDrawValue(true);
                            repaint();
                        }
                        case MouseType.LED -> {
                            circuit.addComponent(org, new Led(org));
                            circuit.getComponentList().getLast().setDrawValue(true);
                            repaint();
                        }
                        case MouseType.Settings -> {
//                            circuit.addComponent(org, new Not(org));
//                            circuit.getComponentList().getLast().setDrawValue(true);
//                            repaint();
                        }
                        case MouseType.Trash -> {
                            try {
                                circuit.deleteComponent(e);
                            }
                            catch(Exception n) {
                            }
                            
                        }
                    }
                }
            }
        });
    }
    
    @Override
    public void paint(Graphics g) 
    {
        super.paint(g);
        for (Component component : circuit.getComponentList())
        {
            if (component.getDrawValue()) 
            {
                component.draw(gp);
            }
  
        }
        for (Wire wire : circuit.getWireList())
        {
           if (wire.getDrawValue())
           {
               wire.draw(gp);
           } 
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbPanel = new javax.swing.JTabbedPane();
        descriptionPanel = new javax.swing.JPanel();
        circuitPanel = new javax.swing.JPanel();
        Circuit = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblCircuitCircuitName = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        drawingZonePanel = new javax.swing.JPanel();
        DrawingZone = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        lblDrawingCircuitName = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        utilitiesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTrash = new javax.swing.JButton();
        btnSimlator = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        componentsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAnd = new javax.swing.JButton();
        btnNAnd = new javax.swing.JButton();
        btnOr = new javax.swing.JButton();
        btnNor = new javax.swing.JButton();
        btnXOr = new javax.swing.JButton();
        btnXNOr = new javax.swing.JButton();
        btnNot = new javax.swing.JButton();
        btnVariable = new javax.swing.JButton();
        btnLed = new javax.swing.JButton();
        DrawingPanel = new javax.swing.JPanel();
        booleanPanel = new javax.swing.JPanel();
        booleanExpresionPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        txt = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        propertiesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout descriptionPanelLayout = new javax.swing.GroupLayout(descriptionPanel);
        descriptionPanel.setLayout(descriptionPanelLayout);
        descriptionPanelLayout.setHorizontalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        descriptionPanelLayout.setVerticalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        tbPanel.addTab("Description", descriptionPanel);

        Circuit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCircuitCircuitName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCircuitCircuitName.setText("Nombre del circuito");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCircuitCircuitName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblCircuitCircuitName)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        bodyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("jLabel3");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton14.setText("jButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addContainerGap())
        );

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton15.setText("jButton15");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addContainerGap())
        );

        jLabel6.setText("jLabel6");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton16.setText("jButton16");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addContainerGap())
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(155, 155, 155)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CircuitLayout = new javax.swing.GroupLayout(Circuit);
        Circuit.setLayout(CircuitLayout);
        CircuitLayout.setHorizontalGroup(
            CircuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CircuitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CircuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        CircuitLayout.setVerticalGroup(
            CircuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CircuitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout circuitPanelLayout = new javax.swing.GroupLayout(circuitPanel);
        circuitPanel.setLayout(circuitPanelLayout);
        circuitPanelLayout.setHorizontalGroup(
            circuitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Circuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        circuitPanelLayout.setVerticalGroup(
            circuitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circuitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Circuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbPanel.addTab("Circuit", circuitPanel);

        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDrawingCircuitName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrawingCircuitName.setText("Nombre del circuito");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDrawingCircuitName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDrawingCircuitName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        utilitiesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tools");

        btnTrash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/trash-can.png"))); // NOI18N
        btnTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrashActionPerformed(evt);
            }
        });

        btnSimlator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/start.png"))); // NOI18N
        btnSimlator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimlatorActionPerformed(evt);
            }
        });

        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/setting.png"))); // NOI18N
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/broom.png"))); // NOI18N
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout utilitiesPanelLayout = new javax.swing.GroupLayout(utilitiesPanel);
        utilitiesPanel.setLayout(utilitiesPanelLayout);
        utilitiesPanelLayout.setHorizontalGroup(
            utilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(utilitiesPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(utilitiesPanelLayout.createSequentialGroup()
                        .addGroup(utilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(utilitiesPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnSimlator, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        utilitiesPanelLayout.setVerticalGroup(
            utilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(utilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrash)
                    .addComponent(btnSettings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(utilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimlator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        componentsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Components");

        btnAnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/And.png"))); // NOI18N
        btnAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndActionPerformed(evt);
            }
        });

        btnNAnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/NAnd.png"))); // NOI18N
        btnNAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNAndActionPerformed(evt);
            }
        });

        btnOr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/Or.png"))); // NOI18N
        btnOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrActionPerformed(evt);
            }
        });

        btnNor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/NOr.png"))); // NOI18N
        btnNor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNorActionPerformed(evt);
            }
        });

        btnXOr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/XOr.png"))); // NOI18N
        btnXOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOrActionPerformed(evt);
            }
        });

        btnXNOr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/XNOr.png"))); // NOI18N
        btnXNOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXNOrActionPerformed(evt);
            }
        });

        btnNot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/Not.png"))); // NOI18N
        btnNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotActionPerformed(evt);
            }
        });

        btnVariable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/switch.png"))); // NOI18N
        btnVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVariableActionPerformed(evt);
            }
        });

        btnLed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Utilities/imagenes/led.png"))); // NOI18N
        btnLed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout componentsPanelLayout = new javax.swing.GroupLayout(componentsPanel);
        componentsPanel.setLayout(componentsPanelLayout);
        componentsPanelLayout.setHorizontalGroup(
            componentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(componentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, componentsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(componentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(componentsPanelLayout.createSequentialGroup()
                                .addComponent(btnOr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(componentsPanelLayout.createSequentialGroup()
                                .addComponent(btnAnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNAnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(componentsPanelLayout.createSequentialGroup()
                                .addComponent(btnXOr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXNOr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(componentsPanelLayout.createSequentialGroup()
                                .addComponent(btnNot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
            .addGroup(componentsPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnLed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        componentsPanelLayout.setVerticalGroup(
            componentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(componentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNAnd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(componentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(componentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXOr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXNOr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(componentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLed, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utilitiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(componentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addComponent(utilitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DrawingPanel.setBackground(new java.awt.Color(255, 255, 255));
        DrawingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DrawingPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DrawingPanelMouseDragged(evt);
            }
        });
        DrawingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DrawingPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DrawingPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DrawingPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DrawingPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DrawingPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout DrawingPanelLayout = new javax.swing.GroupLayout(DrawingPanel);
        DrawingPanel.setLayout(DrawingPanelLayout);
        DrawingPanelLayout.setHorizontalGroup(
            DrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        DrawingPanelLayout.setVerticalGroup(
            DrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DrawingZoneLayout = new javax.swing.GroupLayout(DrawingZone);
        DrawingZone.setLayout(DrawingZoneLayout);
        DrawingZoneLayout.setHorizontalGroup(
            DrawingZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawingZoneLayout.createSequentialGroup()
                .addGroup(DrawingZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DrawingZoneLayout.createSequentialGroup()
                        .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DrawingZoneLayout.setVerticalGroup(
            DrawingZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrawingZoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DrawingZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout drawingZonePanelLayout = new javax.swing.GroupLayout(drawingZonePanel);
        drawingZonePanel.setLayout(drawingZonePanelLayout);
        drawingZonePanelLayout.setHorizontalGroup(
            drawingZonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DrawingZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        drawingZonePanelLayout.setVerticalGroup(
            drawingZonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawingZonePanelLayout.createSequentialGroup()
                .addComponent(DrawingZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbPanel.addTab("Drawing Zone", drawingZonePanel);

        booleanExpresionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre del circuito");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(167, 167, 167))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout booleanExpresionPanelLayout = new javax.swing.GroupLayout(booleanExpresionPanel);
        booleanExpresionPanel.setLayout(booleanExpresionPanelLayout);
        booleanExpresionPanelLayout.setHorizontalGroup(
            booleanExpresionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booleanExpresionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(booleanExpresionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(booleanExpresionPanelLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        booleanExpresionPanelLayout.setVerticalGroup(
            booleanExpresionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booleanExpresionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(booleanExpresionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout booleanPanelLayout = new javax.swing.GroupLayout(booleanPanel);
        booleanPanel.setLayout(booleanPanelLayout);
        booleanPanelLayout.setHorizontalGroup(
            booleanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booleanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(booleanExpresionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        booleanPanelLayout.setVerticalGroup(
            booleanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booleanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(booleanExpresionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbPanel.addTab("Boolean", booleanPanel);

        javax.swing.GroupLayout propertiesPanelLayout = new javax.swing.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        tbPanel.addTab("Properties", propertiesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbPanel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //VARIABLES
    //**************************************************************************
    private static Toolkit tk = Toolkit.getDefaultToolkit();
    
    
    //MOUSE EVENTS
    //**************************************************************************
    private void DrawingPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawingPanelMouseClicked
        // TODO add your handling code here:
        if(circuit.addConection(evt)) repaint();
    }//GEN-LAST:event_DrawingPanelMouseClicked

    private void DrawingPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawingPanelMouseDragged
        // TODO add your handling code here:
        circuit.dragComponent(evt, DrawingPanel.getBounds());
        repaint();
        
    }//GEN-LAST:event_DrawingPanelMouseDragged

    
    private void DrawingPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawingPanelMousePressed
        // TODO add your handling code here:
        circuit.selectComponent(evt);
    }//GEN-LAST:event_DrawingPanelMousePressed

    
    //ADDING COMPONENTS
    //**************************************************************************
    private void btnAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.And )
        {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\And.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "And");
            this.setCursor(custom);
            type = MouseType.And;
        }
        else
        {
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnAndActionPerformed

    private void btnNAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNAndActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.NAnd )
        {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\NAnd.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "NAnd");
            this.setCursor(custom);
            type = MouseType.NAnd;
        }
        else
        {
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnNAndActionPerformed

    private void btnOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.Or )
        {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\Or.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "Or");
            this.setCursor(custom);
            type = MouseType.Or;
        }
        else
        {
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnOrActionPerformed

    private void btnNorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNorActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.NOr ) {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\NOr.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "NOr");
            this.setCursor(custom);
            type = MouseType.NOr;
        }
        else {
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnNorActionPerformed

    private void btnXOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOrActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.XOr ) {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\XOr.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "XOr");
            this.setCursor(custom);
            type = MouseType.XOr;
        }
        else{
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnXOrActionPerformed

    private void btnNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.Not ) {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\Not.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "Not");
            this.setCursor(custom);
            type = MouseType.Not;
        }
        else {
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnNotActionPerformed

    private void DrawingPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawingPanelMouseEntered
        // TODO add your handling code here:
        circuit.mouseOnComponent(evt);
        repaint();
    }//GEN-LAST:event_DrawingPanelMouseEntered

    private void DrawingPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawingPanelMouseExited
        // TODO add your handling code here:
        circuit.mouseNotOnComponent(evt);
        repaint();
    }//GEN-LAST:event_DrawingPanelMouseExited

    private void DrawingPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawingPanelMouseReleased
        // TODO add your handling code here:
        circuit.unSelectComponent(evt);
    }//GEN-LAST:event_DrawingPanelMouseReleased

    private void btnTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrashActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.Trash ) {
//            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\trash-can.png");
//            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "Trash");
            this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            type = MouseType.Trash;
        }
        else{
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnTrashActionPerformed

    private void btnVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVariableActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.Variable ) {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\switch.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "Variable");
            this.setCursor(custom);
            type = MouseType.Variable;
        }
        else{
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnVariableActionPerformed

    private void btnXNOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXNOrActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.XNOr ) {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\XNOr.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "XNOr");
            this.setCursor(custom);
            type = MouseType.XNOr;
        }
        else{
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnXNOrActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, 
                "Do you want to clean the scream?", "Clean option", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        switch (answer) {
            case JOptionPane.YES_OPTION -> {
                circuit.cleanComponents();
                repaint();
            }    
            case JOptionPane.NO_OPTION -> {
                
            }    
            case JOptionPane.CANCEL_OPTION -> {
            
            }    
            
            default -> throw new AssertionError();
        }
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnLedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLedActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.LED ) {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\led.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "LED");
            this.setCursor(custom);
            type = MouseType.LED;
        }
        else{
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnLedActionPerformed

    private void btnSimlatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimlatorActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<6; i++){
            circuit.simulateCircuit();
        }
        repaint();
         
    }//GEN-LAST:event_btnSimlatorActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
        if( type != MouseType.Settings ) {
            Image icon = tk.getImage("C:\\Users\\USUARIO\\Downloads\\LogicGates\\setting.png");
            Cursor custom = tk.createCustomCursor(icon, new Point(0,0), "Setting");
            this.setCursor(custom);
            type = MouseType.Settings;
        }
        else{
            this.setCursor( new Cursor( Cursor.DEFAULT_CURSOR ) );
            type = MouseType.None;
        }
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        circuit.booleanExpresionToDiagram(txt.getText());
//        circuit.drawCircuitFromTree(gp);
//        txt.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Circuit;
    private javax.swing.JPanel DrawingPanel;
    private javax.swing.JPanel DrawingZone;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel booleanExpresionPanel;
    private javax.swing.JPanel booleanPanel;
    private javax.swing.JButton btnAnd;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnLed;
    private javax.swing.JButton btnNAnd;
    private javax.swing.JButton btnNor;
    private javax.swing.JButton btnNot;
    private javax.swing.JButton btnOr;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnSimlator;
    private javax.swing.JButton btnTrash;
    private javax.swing.JButton btnVariable;
    private javax.swing.JButton btnXNOr;
    private javax.swing.JButton btnXOr;
    private javax.swing.JPanel circuitPanel;
    private javax.swing.JPanel componentsPanel;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JPanel drawingZonePanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCircuitCircuitName;
    private javax.swing.JLabel lblDrawingCircuitName;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JTabbedPane tbPanel;
    private javax.swing.JTextField txt;
    private javax.swing.JPanel utilitiesPanel;
    // End of variables declaration//GEN-END:variables
}
