/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Resources.Components.Component;
import Resources.Components.Gates.*;
import Resources.Components.*;
import Resources.Enums.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author ₰Andrés₰
 */
public class temp extends javax.swing.JFrame {
    
    private  List<Component> ComponentList = new LinkedList<>();
    private  ArrayList<Wire> WireList = new ArrayList<>();
    private  Point org = new Point(100,100);
    Pin selectedOutput = null;
    /*
    Component var = new Variable(new Point(100,100), 50,30);
    Led led = new Led(new Point(200,200));
    Switch switcher = new Switch(new Point(100,100), 20);
    Component and = new And(new Point(100,100), 60, 60, 3);
    Component or = new Or(new Point(100,100), 60, 60, 4);
    Component NAnd = new NAnd(new Point(100,100), 60, 60, 3);
    Component nOr = new NOr(new Point(100,100), 60, 60, 4);
    Component xNOr = new XNOr(new Point(100,100), 60, 60, 3);
    Component XOr = new XOr(new Point(100,100), 60, 60, 4);
    Component not = new Not(new Point(100,100));
    //Pin pin = new Pin(new Point(100,100), true, PinID.Input1);
    */
    
    
    /**
     * Creates new form temp
     */
    Graphics x;
    public temp() {
        initComponents();
        x = panel.getGraphics();
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVar = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        btnLed = new javax.swing.JButton();
        btnSwitch = new javax.swing.JButton();
        btnPin = new javax.swing.JButton();
        btnAnd = new javax.swing.JButton();
        btnOr = new javax.swing.JButton();
        btnNot = new javax.swing.JButton();
        btnNand = new javax.swing.JButton();
        btnNor = new javax.swing.JButton();
        btnXor = new javax.swing.JButton();
        btnXnor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVar.setText("Variable");
        btnVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVarActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        btnLed.setText("LED");
        btnLed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLedActionPerformed(evt);
            }
        });

        btnSwitch.setText("Switch");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        btnPin.setText("Pin");
        btnPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinActionPerformed(evt);
            }
        });

        btnAnd.setText("AND");
        btnAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndActionPerformed(evt);
            }
        });

        btnOr.setText("Or");
        btnOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrActionPerformed(evt);
            }
        });

        btnNot.setText("Not");
        btnNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotActionPerformed(evt);
            }
        });

        btnNand.setText("NAND");
        btnNand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNandActionPerformed(evt);
            }
        });

        btnNor.setText("NOR");
        btnNor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNorActionPerformed(evt);
            }
        });

        btnXor.setText("XOR");
        btnXor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXorActionPerformed(evt);
            }
        });

        btnXnor.setText("XNOR");
        btnXnor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXnorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVar)
                                    .addComponent(btnPin))
                                .addComponent(btnAnd))
                            .addComponent(btnOr))
                        .addComponent(btnNot))
                    .addComponent(btnLed)
                    .addComponent(btnSwitch)
                    .addComponent(btnNand)
                    .addComponent(btnNor)
                    .addComponent(btnXor)
                    .addComponent(btnXnor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLed)
                .addGap(12, 12, 12)
                .addComponent(btnSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXnor)
                .addContainerGap(110, Short.MAX_VALUE))
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public void paint(Graphics g) 
    {
        super.paint(g);
        for (Component component : ComponentList)
        {
            if (component.getDrawValue()) 
            {
                component.draw(x);
            }
  
        }
        for (Wire wire : WireList)
        {
           if (wire.getDrawValue())
           {
               wire.draw(x);
           } 
        }
    }

    private void btnVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVarActionPerformed
        // TODO add your handling code here:
        ComponentList.add(new Variable(org));
        ComponentList.getLast().setDrawValue(true);
        repaint();
    }//GEN-LAST:event_btnVarActionPerformed

    private void btnLedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLedActionPerformed
        // TODO add your handling code here:
        ComponentList.add(new Led(new Point(200,200)));
        ComponentList.getLast().setDrawValue(true);
        repaint();
    }//GEN-LAST:event_btnLedActionPerformed

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        // TODO add your handling code here:
//        switcher.setSwtichValue(1);
//        switcher.setMouseOnIt(true);
//        switcher.draw(x);
        
    }//GEN-LAST:event_btnSwitchActionPerformed

    private void btnPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinActionPerformed
        // TODO ad
        
    }//GEN-LAST:event_btnPinActionPerformed

    private void btnAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndActionPerformed
        // TODO add your handling code here:
        ComponentList.add(new And(org));
        ComponentList.getLast().setDrawValue(true);
        repaint();
    }//GEN-LAST:event_btnAndActionPerformed

    private void btnOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrActionPerformed
        // TODO add your handling code here:
        ComponentList.add(new Or(org));
        ComponentList.getLast().setDrawValue(true);
        repaint();
    }//GEN-LAST:event_btnOrActionPerformed

    private void btnNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotActionPerformed
        ComponentList.add(new Not(org));
        ComponentList.getLast().setDrawValue(true);
        repaint();
    }//GEN-LAST:event_btnNotActionPerformed

    private void btnNandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNandActionPerformed
        // TODO add your handling code here:
        ComponentList.add(new NAnd(org));
        ComponentList.getLast().setDrawValue(true);
        repaint();
    }//GEN-LAST:event_btnNandActionPerformed

    private void btnNorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNorActionPerformed
        ComponentList.add(new NOr(org));
        ComponentList.getLast().setDrawValue(true);
        repaint();
    }//GEN-LAST:event_btnNorActionPerformed

    private void btnXorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXorActionPerformed
    ComponentList.add(new XOr(org));
        ComponentList.getLast().setDrawValue(true);
        repaint();
    }//GEN-LAST:event_btnXorActionPerformed

    private void btnXnorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXnorActionPerformed
   ComponentList.add(new XNOr(org));
        ComponentList.getLast().setDrawValue(true);
        repaint();
    }//GEN-LAST:event_btnXnorActionPerformed

    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
        for (Component component : ComponentList)
        {
            for (Pin pin : component.getPinsList()) 
            {
                if (pin.isIn(evt.getX(), evt.getY())) 
                {
                    if (!pin.getPinType()) 
                    {
                        selectedOutput = pin;
                    }
                    else if (selectedOutput != null)
                    {
                    
                       WireList.add(new Wire(selectedOutput,pin));
                       WireList.getLast().setDrawValue(true);
                       selectedOutput = null;
                        repaint();
                    }
                    
                }
            }
   
        }
    }//GEN-LAST:event_panelMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new temp().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnd;
    private javax.swing.JButton btnLed;
    private javax.swing.JButton btnNand;
    private javax.swing.JButton btnNor;
    private javax.swing.JButton btnNot;
    private javax.swing.JButton btnOr;
    private javax.swing.JButton btnPin;
    private javax.swing.JButton btnSwitch;
    private javax.swing.JButton btnVar;
    private javax.swing.JButton btnXnor;
    private javax.swing.JButton btnXor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
